### PR TITLE
[QMediaNetworkPlaylistProvider] Upon error parsing, stop parsing.

### PR DESCRIPTION
**Pull request by tanty**
When an error is found parsing a playlist, stop
parsing. This will also prevent the emission of
the "loaded" signal when the parser finishes.

### CODE REVIEW

**Comment by rburchell** [comment]
This needs to go upstream first. I'll send it there, as I guess you haven't done that before. If you're going to be working on Qt regularly though, it might be good to get familiar with the proceedure (and get on the Jolla CLA)

**Comment by tanty** [comment]
I opened and provided a patch at:
https://bugreports.qt-project.org/browse/QTBUG-40513

From your comment, I suppose that's not enough :)

**Comment by rburchell** [comment]
Yeah, unfortunately, patches can't be taken through JIRA for licensing reasons (submitter needs to have a CLA on hand). Thanks, though, that's helpful still!

Patch submission can be done using Gerrit (http://qt-project.org/wiki/Setting-up-Gerrit - https://codereview.qt-project.org/#/)

**Comment by rburchell** [comment]
merged by hand

**Pull request closed without merging**
